#if !canImport(ObjectiveC)
import XCTest

extension CodeCompletionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodeCompletionTests = [
        ("testCompletionAfterEdit", testCompletionAfterEdit),
        ("testCompletionFiltering", testCompletionFiltering),
        ("testSimpleCompletion", testSimpleCompletion),
        ("testStressEdits", testStressEdits),
    ]
}

extension EditorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EditorTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodeCompletionTests.__allTests__CodeCompletionTests),
        testCase(EditorTests.__allTests__EditorTests),
    ]
}
#endif
